TENSORBOARD_EXPERIMENT: "/home/sgiit/disk_2T/Train_Models/DOTA/logs/dota_dcn_weightAL5"
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1024
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: False
    DEFORMABLE_GROUPS: 1
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    ASPECT_RATIOS: (1.0, )
  ROI_HEADS:
    USE_FPN: True
    LAMDA_INTEGRATED: True
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0, 5.0)
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictorWithAngleIntegrated"
    NUM_CLASSES: 19
DATASETS:
  TRAIN: ("dota",)
  TEST: ("dota_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: False
SOLVER:
  # Assume 8 gpus
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (800000, 1000000)
  MAX_ITER: 1500000
  IMS_PER_BATCH: 8
TEST:
  IMS_PER_BATCH: 4
