TENSORBOARD_EXPERIMENT: "logs/ship_detect_weightAL10"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    ASPECT_RATIOS: (1.0,)
  ROI_HEADS:
    USE_FPN: True
    LAMDA_INTEGRATED: True
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0, 10.0)
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictorWithAngleIntegrated"
    NUM_CLASSES: 29
DATASETS:
  TRAIN: ("hrsc",)
  TEST: ("hrsc_val",)
INPUT:
  MIN_SIZE_TRAIN: (500,)
  MAX_SIZE_TRAIN: 1300
  MIN_SIZE_TEST: 481
  MAX_SIZE_TEST: 1238
DATALOADER:
  ASPECT_RATIO_GROUPING: False
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 100000
  IMS_PER_BATCH: 16
