TENSORBOARD_EXPERIMENT: "/home/sgiit/disk_2T/Train_Models/hrsc/logs/dota_mdcn_weightAL5"
OUTPUT_DIR: "/home/sgiit/disk_2T/Train_Models/HRSC/hrsc_mdconv_R_50_FPN_1x_weight_AL5"
INPUT:
  MIN_SIZE_TRAIN: (500,)
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 481
  MAX_SIZE_TEST: 1238
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: True
    DEFORMABLE_GROUPS: 1
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (128, 256, 512, 1024)
    ANCHOR_STRIDE: (2, 4, 8, 16)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    ASPECT_RATIOS: (0.5, 1.0, 2.0, 4.0)
  ROI_HEADS:
    USE_FPN: True
    LAMDA_INTEGRATED: True
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0, 5.0)
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictorWithAngleIntegrated"
    NUM_CLASSES: 29
DATASETS:
  TRAIN: ("hrsc",)
  TEST: ("hrsc_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: False
SOLVER:
  # Assume 8 gpus
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, 80000)
  MAX_ITER: 100000
  IMS_PER_BATCH: 8
TEST:
  IMS_PER_BATCH: 4